2025-07-05 00:09:00.252849 - Error in train_from_deck:
train_model_on_text() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/__init__.py", line 1346, in run_training
    train_model_on_text(combined_content, combined_content)
TypeError: train_model_on_text() takes 1 positional argument but 2 were given

2025-08-09 16:41:46.985688 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (unknown location)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 87, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (unknown location)


2025-08-09 16:41:48.893176 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (unknown location)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 87, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (unknown location)


2025-08-09 16:45:58.459218 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 87, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:46:00.538801 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 87, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:46:59.220919 - Error in train_from_deck:
No module named 'ClientAuth'
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 41, in train_model_on_text
    from src.ClientAuth import AuthClient
ModuleNotFoundError: No module named 'ClientAuth'


2025-08-09 16:47:01.298322 - Error in train_from_deck:
No module named 'ClientAuth'
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 41, in train_model_on_text
    from src.ClientAuth import AuthClient
ModuleNotFoundError: No module named 'ClientAuth'


2025-08-09 16:48:23.071308 - Error in train_from_deck:
No module named 'src'
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 41, in train_model_on_text
    from .ClientAuth import AuthClient
ModuleNotFoundError: No module named 'src'


2025-08-09 16:48:25.467811 - Error in train_from_deck:
No module named 'src'
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 41, in train_model_on_text
    from .ClientAuth import AuthClient
ModuleNotFoundError: No module named 'src'


2025-08-09 16:49:45.362617 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 87, in train_model_on_text
    # Wait for the worker to finish
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:49:47.044645 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 87, in train_model_on_text
    # Wait for the worker to finish
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:50:33.870250 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:50:36.253218 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:53:40.072856 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:53:42.223051 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:54:17.783071 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 16:54:19.525160 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 17:05:29.440089 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 17:05:32.604510 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 17:07:03.706081 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 17:07:05.923289 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 17:08:25.004913 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 17:08:27.367581 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:44:04.720772 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:44:29.234680 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:49:12.104094 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:49:18.773273 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 72, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:54:01.233901 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 73, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:54:02.912877 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 73, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:59:22.025404 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 73, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 19:59:36.555127 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 73, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:00:37.872132 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 86, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:00:39.989343 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 86, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:02:44.456182 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 82, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:02:45.556134 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 82, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:03:50.901186 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:03:51.745791 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:05:32.619872 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:05:33.818473 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:07:24.339081 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:07:25.569080 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:11:42.106063 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:11:43.841796 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:13:25.362048 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:13:27.880454 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:13:45.262114 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:13:46.066845 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:17:59.428957 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 84, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:18:01.023872 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 84, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:24:46.861150 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:24:48.823140 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:26:50.971085 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:26:52.121694 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:28:26.439436 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:28:27.853834 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:35:09.377462 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:35:11.718906 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:42:01.848910 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:42:03.384881 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-09 20:47:21.519328 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-10 10:23:18.085787 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-11 18:20:28.928515 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-11 18:20:30.811958 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-11 18:29:38.272818 - Error in train_from_deck:
Error generating questions: Not authenticated. Please log in first.
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: Not authenticated. Please log in first.


2025-08-11 18:29:39.326527 - Error in train_from_deck:
Error generating questions: Not authenticated. Please log in first.
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: Not authenticated. Please log in first.


2025-08-11 18:29:42.430708 - Error in train_from_deck:
Error generating questions: Not authenticated. Please log in first.
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: Not authenticated. Please log in first.


2025-08-11 18:30:06.915039 - Error in train_from_deck:
Error generating questions: Not authenticated. Please log in first.
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: Not authenticated. Please log in first.


2025-08-11 18:30:07.830667 - Error in train_from_deck:
Error generating questions: Not authenticated. Please log in first.
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: Not authenticated. Please log in first.


2025-08-11 18:31:17.743374 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-11 18:31:18.624516 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-11 18:39:45.221282 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


2025-08-11 18:39:53.854837 - Error in train_from_deck:
Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)
Traceback (most recent call last):
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/training/deck_training.py", line 83, in train_from_deck
    train_model_on_text(combined_content)
  File "/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/pdf_training.py", line 91, in train_model_on_text
    raise Exception(error_message["msg"])
Exception: Error generating questions: cannot import name 'auth_client' from 'AnkiExam_Addon.src' (/Users/colestocker/Library/Application Support/Anki2/addons21/AnkiExam_Addon/src/__init__.py)


